change from ansible to ansible-base as dependency
networktocode/schema-enforcer pull request #92
Opened 2021-02-13 15:15 UTC by itdependsnetworks

While our "slim" strategy is clear, it still does not make sense to include the entire ansible package even in the batteries included approach. I believe it is reasonable to only support from ansible 2.10 and on. 

Additionally, with the cryptography chaos, I purposefully let the package move to 3.4.x, figure we should get this behind us now while the project is newer. 

I would recommend a version bump after this as well.

2021-02-16 15:27 UTC, PhillSimonds commented
CI is currently evaluating multiple versions of Ansible. I think we'd want to change the `.travis.yml` to build correctly as well if we're removing support for 2.8 and 2.9

```yaml
env:
  matrix:
    - "ANSIBLE_VER=2.8.18"
    - "ANSIBLE_VER=2.9.17"
    - "ANSIBLE_VER=2.10.5"
```

The container used for CI tests is doing a `pip uninstall ansible` if that `ANSIBLE_VER` param is specified, then doing a `pip install ansible==$ANSIBLE_VER`

2021-02-16 15:28 UTC, PhillSimonds requested changes
CI is currently evaluating multiple versions of Ansible. I think we'd want to change the `.travis.yml` to build correctly as well if we're removing support for 2.8 and 2.9

```yaml
env:
  matrix:
    - "ANSIBLE_VER=2.8.18"
    - "ANSIBLE_VER=2.9.17"
    - "ANSIBLE_VER=2.10.5"
```

The container used for CI tests is doing a `pip uninstall ansible` if that `ANSIBLE_VER` param is specified, then doing a `pip install ansible==$ANSIBLE_VER`

2021-02-17 11:00 UTC, dgarros commented
I don't think this approach is practical because it will make it really difficult to use the schema-enforcer, if not impossible, for users that are not using Ansible 2.10 yet. 
Also, in the next release Ansible will rename `ansible-base` to `ansible-core` so we'll need to change it again and it will become an issue for 2.10 users as well.

I think we should remove Ansible as a dependencies all together and let users install it on their own, if they want it. 
My guess is : In the majority of cases, Ansible will already be installed so it's a non problem.  If there is an Ansible inventory to validate, it would be surprising if Ansible wasn't already installed :)

When we execute the `schema-enforcer ansible` command we just need to check if Ansible is installed and if not, print a message to explains that Ansible must be installed separately. It's a common practice in other library, including Ansible that is doing that for most modules and filters: `json_query` filter requires `jmespath` to be installed ... 

For convenience, we could publish multiple `extras` to install the schema-enforcer and different flavor of Ansible at the same time:
- `schema-enforcer` > Base version without Ansible
- `schema-enforcer[ansible]` > Base Version + Ansible
- `schema-enforcer[ansible-core]` > Base version + Ansible core

2021-03-01 18:01 UTC, ryanmerolle commented
> I think we should remove Ansible as a dependencies all together and let users install it on their own, if they want it.
> My guess is : In the majority of cases, Ansible will already be installed so it's a non problem. If there is an Ansible inventory to validate, it would be surprising if Ansible wasn't already installed :)

I agree 100%.  This should not be a big change either.

2021-04-20 05:21 UTC, PhillSimonds commented
Closing this PR in favor of the code implented [here](https://github.com/networktocode/schema-enforcer/pull/101)

2021-04-20 05:21 UTC, closed without merging